### ISSUE TITLE
A user, who has OWNER permission, get the crash when decrypting the content expiration document

### ISSUE THREAD

**Issue by Kammy6679** [AzureAD/rms-sdk-for-cpp#73]
A user, who is not the owner, but has OWNER permission. This user gets the crash when decrypting the content expiration document. But the owner can open this content expiration document.

please use your sample to reproduce this issue:
1. download the sample files from: http://1drv.ms/1L3yBXC
Owner: mingjian_chen@msopentechtest01.onmicrosoft.com
PSW: Test,123
2. Run your sample
3. Set "Client Email" to  chengzhang_lin@msopentechtest01.onmicrosoft.com  (PSW:  Foxit2015)
4. Click "Decrypt PFILE"

**Comment by AgentRX** [comment]
When content expired rms crashed. Now it fixed in PR: https://github.com/AzureAD/rms-sdk-for-cpp/pull/74

**Comment by prvijay** [comment]
Andrei - Johnny is indicating that the issue still exists, can you please look into it?

**Comment by AgentRX** [comment]
@Kammy6679, please delete old libraries and samples and recompile whole sdk and samples!
New result should be like this
![screenshot from 2015-08-12 06 50 40](https://cloud.githubusercontent.com/assets/10774820/9249741/71a06e72-41d0-11e5-8fd9-ed80786b26de.png)

**Comment by Kammy6679** [comment]
Thank you. It has been fixed.
